#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo
  echo "Submit molpro job to the queue"
  echo ""
  echo "Usage: $(basename "$0") <molpro input> [--mv YY] [--mppx] [sbatch options]"
  echo
  echo "  --mppx: run Molpro in parallel task mode (e.g., for numerical Hessians)"
  echo "  --mv attribute: select a specific version. e.g. qchem.molpro-ext"
  echo
  exit
fi

inp=$1
shift

# default attribute
vers="qchem.molpro"

opts=("--mppx" "--mv")
extra_opts='--launcher "mpiexec.hydra -np \$SLURM_CPUS_PER_TASK molpro.exe"'

for i in "${opts[@]}"; do
  if [ "$1" == "--mppx" ]; then
    extra_opts="--mppx $extra_opts"
    shift
  fi
  if [ "$1" == "--mv" ]; then
    vers="$2"
    shift 2
  fi
done


cat << EOF | sbatch "$@"
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p $vers
#SBATCH -J molpro
#SBATCH -c 1
export OMP_NUM_THREADS=1

# srun gets confused by CPU binding
export SLURM_CPU_BIND=none

molpro $extra_opts $inp
EOF

